services: 
    app:
        image: registry.cn-beijing.aliyuncs.com/selfdriveguard/sdg-server:0.3.2
        ports:
            - "8000:8000"
        environment: 
            REDIS_HOST: "sdgv2app.redis.rds.aliyuncs.com"
            REDIS_PORT: "6379"
            REDIS_DB: "0"
            REDIS_PASSWORD: "GuardStrike@123"
            MONGO_CONNECTION_STRING: "mongodb://sdg:sdg3App3@dds-2zeb146fafba16441401-pub.mongodb.rds.aliyuncs.com:3717,dds-2zeb146fafba16442383-pub.mongodb.rds.aliyuncs.com:3717/admin?replicaSet=mgset-54022070"
            MONGO_DB_NAME: "sdgApp2"