to_english = {
    '用户名或密码错误': 'wrong user name or password',
    '密码校验失败': 'Password verification failed',
    '用户不存在': 'User does not exist',
    '车辆名称已存在，请更换': 'The vehicle name already exists, please replace',
    '动力学模型不存在': 'Kinetic model does not exist',
    '传感器模型不存在': 'sensor model does not exist',
    '车辆不存在': 'vehicle does not exist',
    '系统内置车辆不可更改': 'Vehicles built into the system cannot be changed',
    '存在重名的传感器信息': 'Sensor information with the same name exists',
    '系统内置车辆不可删除': 'Vehicles built into the system cannot be deleted',
    '存在未处理的作业信息': 'There are unprocessed job information',
    '传感器不存在': 'sensor not present',
    '动力学模型名称已存在': 'Kinetic model name already exists',
    '系统动力学模型不能删除': 'System Dynamics models cannot be deleted',
    '存在未处理的主车信息': 'There is unprocessed master vehicle information',
    '系统动力学模型不可更改': 'The system dynamics model cannot be changed',
    '动力学模型名称已存在，请更换': 'Kinetic model name already exists, please replace',
    '评价准则已存在': 'Evaluation criteria already exist',
    '存在错误评价准则id': 'There is an error evaluation criterion id',
    '系统评价准则不可删除': 'Systematic review criteria cannot be deleted',
    '错误评价准则': 'Error Evaluation Criterion',
    '存在未处理的场景信息': 'There is unprocessed scene information',
    '评价准则不存在': 'Evaluation criteria do not exist',
    '系统评价准则不可编辑': 'Systematic review criteria cannot be edited',
    '评价标准名称已存在，请更换': 'The evaluation criterion name already exists, please replace it',
    '作业名称已存在': 'job name already exists',
    '主车信息不存在': 'The main vehicle information does not exist',
    '主车上没有添加传感器': 'No sensors added to the main car',
    '传感器信息不存在': 'Sensor information does not exist',
    '场景存在异常，检查是否有无效场景': 'There is an exception in the scene, check whether there is an invalid scene',
    '场景名称超过了64个字符': 'The scene name exceeds 64 characters',
    '作业不存在': 'job does not exist',
    '作业状态错误': 'job status error',
    '场景不存在，检查作业是否存在场景': 'The scene does not exist, check whether the job has a scene',
    '任务不存在': 'task does not exist',
    '未添加要删除作业id': 'The job id to be deleted is not added',
    '仅支持删除已完成和未运行状态作业': 'Only supports deletion of completed and not running status jobs',
    '存在错误的任务id': 'wrong task id',
    '主车上传感器不存在': 'The sensor on the main vehicle does not exist',
    'evaluation_standard not exits': 'evaluation_standard not exits',
    '仅支持已完成状态任务信息查询': 'Only supports completed status task information query',
    '作业信息不存在': 'Job information does not exist',
    '格式化失败': 'Formatting failed',
    '仅提供完成状态的作业测试报告': 'Job test reports with completion status only',
    '生成测试报告失败': 'Failed to generate test report',
    '传感器数据不存在': 'Sensor data does not exist',
    '文件不存在': 'file does not exist',
    '提交失败请重试': 'Submit failed, please try again',
    '光照信息已存在': 'Lighting information already exists',
    '存在错误的光照id': 'There is a wrong light id',
    '系统内置光照参数不能删除': 'System built-in lighting parameters cannot be deleted',
    '光照信息不存在': 'Lighting information does not exist',
    '系统内置光照参数不可更改': 'The built-in lighting parameters of the system cannot be changed',
    '光照名称已存在，请更换': 'Light name already exists, please replace',
    '场景已存在': 'scene already exists',
    '场景不存在': 'scene does not exist',
    '系统场景不可删除': 'System scenes cannot be deleted',
    '系统场景不可编辑': 'System scenes are not editable',
    '场景名称已存在，请更换': 'The scene name already exists, please replace',
    '存在错误的场景信息': 'There is wrong scene information',
    '场景分组不存在': 'Scene group does not exist',
    '场景组名称已存在，请更换': 'The scene group name already exists, please replace it',
    '场景文件夹不存在': 'scene folder does not exist',
    '系统场景不可更改': 'The system scene cannot be changed',
    '场景名称已修改': 'The scene name has been modified',
    '存在错误的场景': 'There is an error scene',
    '分组下存在相同的名称': 'The same name exists under the group',
    '场景格式转换失败': 'Scene format conversion failed',
    '场景格式不合规': 'Scene format is not compliant',
    '存在无效的场景': 'There is an invalid scene',
    '非管理员不可上传': 'Non-administrators cannot upload',
    '下载目录与下载数量不一致': 'The download directory does not match the number of downloads',
    '不支持的下载文件类型': 'Unsupported download file type',
    '目标路径与文件数量不匹配': 'Destination path does not match number of files',
    '不支持上传的文件类型': 'The uploaded file type is not supported',
    '保存路径不存在': 'save path does not exist',
    '传感器名称已存在': 'sensor name already exists',
    '系统内置传感器不能删除': 'System built-in sensors cannot be deleted',
    '存在未处理的车辆信息': 'Unprocessed vehicle information exists',
    '系统内置传感器不能修改': 'System built-in sensors cannot be modified',
    '传感器名称已存在，请更换': 'Sensor name already exists, please replace',
    '回收站信息不存在': 'Recycle bin information does not exist',
    '恢复目标文件夹不存在': 'The recovery target folder does not exist',
    '恢复目录已有同名文件,无法恢复': 'The recovery directory already has a file with the same name and cannot be recovered',
    '上传失败': 'upload failed',
    '删除当前角色失败': 'Failed to delete current role',
    '添加用户角色失败': 'Failed to add user role',
    '用户已存在': 'user already exists',
    '体验版不能添加用户': 'The trial version cannot add users',
    '角色类型错误': 'wrong role type',
    '天气名称已存在，请更换': 'The weather name already exists, please replace',
    '存在错误的天气id': 'Wrong weather id exists',
    '系统内置天气不可删除': 'The system built-in weather cannot be deleted',
    '天气信息不存在': 'weather information does not exist',
    '系统内置天气参数不可修改': 'The built-in weather parameters of the system cannot be modified',
    '请求失败': 'request failure',
    '邮箱格式不合规': 'eamil invalid',
}
